### ISSUE TITLE
OpenFashion TODO

### ISSUE THREAD

**Issue by vikramvaibhav** [vikramvaibhav/OpenFashion#6]
OpenFashion TODO

- [x] Add Navigation
- [ ] Dynamic route generation
- [ ] Convert to modules
- [ ] Jest setup
- [ ] No Network / No Internet warning
- [ ] Redux setup & persist
- [ ] Lottie view add one animation / loading
- [ ] Open eCommerce API integration
- [ ] Form setup - React hook / Formik
- [ ] Lint setup
- [ ] Async storage setup / encrypted storage
- [ ] Firebase authentication
